version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    ports:
      - "9999:9999"
      - "8180:8180"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: api
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
#      - "traefik.http.routers.api.entrypoints=web"
#      - "traefik.http.routers.api.service=api"
#      - "traefik.http.routers.api.middlewares=api-strip@docker,cors@file"
#      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
#      - "traefik.http.services.api.loadbalancer.server.port=8080"
#    networks:
#      - proxy
#    restart: unless-stopped

networks:
  proxy:
    driver: bridge
